# Generated by Django 5.2.13 on 2026-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_basepair_id_alter_helice_id_alter_log_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleotide",
            name="sugar_pucker",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="quadruplex",
            name="bulges",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quadruplex",
            name="handedness",
            field=models.CharField(
                blank=True,
                choices=[("right", "right"), ("left", "left")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quadruplex",
            name="path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quadruplex",
            name="strand_polarities",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quadruplex",
            name="tetrad_polarities",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tetradorequest",
            name="quadruplex_dot_bracket_chi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tetradorequest",
            name="quadruplex_dot_bracket_loop",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tetradorequest",
            name="quadruplex_dot_bracket_sequence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tetradorequest",
            name="quadruplex_dot_bracket_structure",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tetradorequest",
            name="quadruplex_dot_bracket_sugar",
            field=models.TextField(blank=True),
        ),
    ]
