# Generated by Django 5.2.13 on 2026-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_nucleotide_sugar_pucker_quadruplex_bulges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadruplex",
            name="tracts",
            field=models.TextField(blank=True, default=""),
        ),
    ]
